---
deployment:
  tasks:
    - export DEPLOYPATH=/home7/teamdigi/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R como-trabajamos $DEPLOYPATH
    - /bin/cp -R contacto $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R sobre-nosotros $DEPLOYPATH
    - /bin/cp ejemplo.txt $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH